--
-- PostgreSQL database dump
--

\restrict cvvhlijhVxMYO4RNLKrHPOVQFc7BZrE5dzU3bzXdW5UuPfFQiDXS39YAj9E5o4d

-- Dumped from database version 16.13 (Ubuntu 16.13-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.13 (Ubuntu 16.13-0ubuntu0.24.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: api_about; Type: TABLE; Schema: public; Owner: cv_user
--

CREATE TABLE public.api_about (
    id bigint NOT NULL,
    headline character varying(200) NOT NULL,
    summary text NOT NULL,
    profile_id bigint NOT NULL
);


ALTER TABLE public.api_about OWNER TO cv_user;

--
-- Name: api_about_id_seq; Type: SEQUENCE; Schema: public; Owner: cv_user
--

ALTER TABLE public.api_about ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_about_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_aboutparagraph; Type: TABLE; Schema: public; Owner: cv_user
--

CREATE TABLE public.api_aboutparagraph (
    id bigint NOT NULL,
    content text NOT NULL,
    "order" integer NOT NULL,
    about_id bigint NOT NULL,
    CONSTRAINT api_aboutparagraph_order_check CHECK (("order" >= 0))
);


ALTER TABLE public.api_aboutparagraph OWNER TO cv_user;

--
-- Name: api_aboutparagraph_id_seq; Type: SEQUENCE; Schema: public; Owner: cv_user
--

ALTER TABLE public.api_aboutparagraph ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_aboutparagraph_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_architecture; Type: TABLE; Schema: public; Owner: cv_user
--

CREATE TABLE public.api_architecture (
    id bigint NOT NULL,
    title character varying(255) NOT NULL,
    description text NOT NULL,
    image character varying(100),
    "order" integer NOT NULL
);


ALTER TABLE public.api_architecture OWNER TO cv_user;

--
-- Name: api_architecture_id_seq; Type: SEQUENCE; Schema: public; Owner: cv_user
--

ALTER TABLE public.api_architecture ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_architecture_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_architecturelink; Type: TABLE; Schema: public; Owner: cv_user
--

CREATE TABLE public.api_architecturelink (
    id bigint NOT NULL,
    label character varying(100) NOT NULL,
    href character varying(200) NOT NULL,
    "order" integer NOT NULL,
    architecture_id bigint NOT NULL
);


ALTER TABLE public.api_architecturelink OWNER TO cv_user;

--
-- Name: api_architecturelink_id_seq; Type: SEQUENCE; Schema: public; Owner: cv_user
--

ALTER TABLE public.api_architecturelink ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_architecturelink_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_architectureservice; Type: TABLE; Schema: public; Owner: cv_user
--

CREATE TABLE public.api_architectureservice (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    "order" integer NOT NULL,
    architecture_id bigint NOT NULL
);


ALTER TABLE public.api_architectureservice OWNER TO cv_user;

--
-- Name: api_architectureservice_id_seq; Type: SEQUENCE; Schema: public; Owner: cv_user
--

ALTER TABLE public.api_architectureservice ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_architectureservice_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_article; Type: TABLE; Schema: public; Owner: cv_user
--

CREATE TABLE public.api_article (
    id bigint NOT NULL,
    title character varying(255) NOT NULL,
    description text NOT NULL,
    body text NOT NULL,
    tags character varying(255) NOT NULL,
    slug character varying(50) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


ALTER TABLE public.api_article OWNER TO cv_user;

--
-- Name: api_article_id_seq; Type: SEQUENCE; Schema: public; Owner: cv_user
--

ALTER TABLE public.api_article ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_article_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_corestrength; Type: TABLE; Schema: public; Owner: cv_user
--

CREATE TABLE public.api_corestrength (
    id bigint NOT NULL,
    pillar character varying(120) NOT NULL,
    description text NOT NULL,
    "order" integer NOT NULL,
    about_id bigint NOT NULL,
    CONSTRAINT api_corestrength_order_check CHECK (("order" >= 0))
);


ALTER TABLE public.api_corestrength OWNER TO cv_user;

--
-- Name: api_corestrength_id_seq; Type: SEQUENCE; Schema: public; Owner: cv_user
--

ALTER TABLE public.api_corestrength ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_corestrength_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_duty; Type: TABLE; Schema: public; Owner: cv_user
--

CREATE TABLE public.api_duty (
    id bigint NOT NULL,
    description character varying(255) NOT NULL,
    "order" integer NOT NULL,
    experience_id bigint NOT NULL,
    CONSTRAINT api_duty_order_check CHECK (("order" >= 0))
);


ALTER TABLE public.api_duty OWNER TO cv_user;

--
-- Name: api_duty_id_seq; Type: SEQUENCE; Schema: public; Owner: cv_user
--

ALTER TABLE public.api_duty ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_duty_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_education; Type: TABLE; Schema: public; Owner: cv_user
--

CREATE TABLE public.api_education (
    id bigint NOT NULL,
    institution character varying(120) NOT NULL,
    qualification character varying(120) NOT NULL,
    start_year integer NOT NULL,
    end_year integer,
    profile_id bigint NOT NULL,
    "order" integer NOT NULL,
    description text NOT NULL,
    CONSTRAINT api_education_end_year_check CHECK ((end_year >= 0)),
    CONSTRAINT api_education_order_check CHECK (("order" >= 0)),
    CONSTRAINT api_education_start_year_check CHECK ((start_year >= 0))
);


ALTER TABLE public.api_education OWNER TO cv_user;

--
-- Name: api_education_id_seq; Type: SEQUENCE; Schema: public; Owner: cv_user
--

ALTER TABLE public.api_education ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_education_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_experience; Type: TABLE; Schema: public; Owner: cv_user
--

CREATE TABLE public.api_experience (
    id bigint NOT NULL,
    company character varying(120) NOT NULL,
    role character varying(120) NOT NULL,
    start_date date NOT NULL,
    end_date date,
    description text NOT NULL,
    "order" integer NOT NULL,
    profile_id bigint NOT NULL,
    CONSTRAINT api_experience_order_check CHECK (("order" >= 0))
);


ALTER TABLE public.api_experience OWNER TO cv_user;

--
-- Name: api_experience_id_seq; Type: SEQUENCE; Schema: public; Owner: cv_user
--

ALTER TABLE public.api_experience ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_experience_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_featuredproject; Type: TABLE; Schema: public; Owner: cv_user
--

CREATE TABLE public.api_featuredproject (
    id bigint NOT NULL,
    title character varying(255) NOT NULL,
    description text NOT NULL,
    features text NOT NULL,
    demo_link character varying(200) NOT NULL,
    github character varying(200) NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    is_featured boolean NOT NULL,
    "order" integer NOT NULL,
    CONSTRAINT api_featuredproject_order_check CHECK (("order" >= 0))
);


ALTER TABLE public.api_featuredproject OWNER TO cv_user;

--
-- Name: api_featuredproject_id_seq; Type: SEQUENCE; Schema: public; Owner: cv_user
--

ALTER TABLE public.api_featuredproject ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_featuredproject_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_hero; Type: TABLE; Schema: public; Owner: cv_user
--

CREATE TABLE public.api_hero (
    id bigint NOT NULL,
    heading character varying(255) NOT NULL,
    subheading character varying(255) NOT NULL,
    cta_text character varying(255) NOT NULL,
    "order" integer NOT NULL,
    CONSTRAINT api_hero_order_check CHECK (("order" >= 0))
);


ALTER TABLE public.api_hero OWNER TO cv_user;

--
-- Name: api_hero_id_seq; Type: SEQUENCE; Schema: public; Owner: cv_user
--

ALTER TABLE public.api_hero ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_hero_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_profile; Type: TABLE; Schema: public; Owner: cv_user
--

CREATE TABLE public.api_profile (
    id bigint NOT NULL,
    name character varying(120) NOT NULL,
    title character varying(120) NOT NULL,
    "interestStatement" text NOT NULL,
    location character varying(120) NOT NULL,
    email character varying(254) NOT NULL,
    github character varying(200) NOT NULL,
    "linkedIn" character varying(200) NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    "resumeLink" character varying(200) NOT NULL,
    user_id integer
);


ALTER TABLE public.api_profile OWNER TO cv_user;

--
-- Name: api_profile_id_seq; Type: SEQUENCE; Schema: public; Owner: cv_user
--

ALTER TABLE public.api_profile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_profile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_profileskill; Type: TABLE; Schema: public; Owner: cv_user
--

CREATE TABLE public.api_profileskill (
    id bigint NOT NULL,
    profile_id bigint NOT NULL,
    skill_id bigint NOT NULL
);


ALTER TABLE public.api_profileskill OWNER TO cv_user;

--
-- Name: api_profileskill_id_seq; Type: SEQUENCE; Schema: public; Owner: cv_user
--

ALTER TABLE public.api_profileskill ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_profileskill_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_skill; Type: TABLE; Schema: public; Owner: cv_user
--

CREATE TABLE public.api_skill (
    id bigint NOT NULL,
    name character varying(80) NOT NULL
);


ALTER TABLE public.api_skill OWNER TO cv_user;

--
-- Name: api_skill_id_seq; Type: SEQUENCE; Schema: public; Owner: cv_user
--

ALTER TABLE public.api_skill ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_skill_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_skillcategory; Type: TABLE; Schema: public; Owner: cv_user
--

CREATE TABLE public.api_skillcategory (
    id bigint NOT NULL,
    category character varying(200) NOT NULL,
    "order" integer NOT NULL,
    CONSTRAINT api_skillcategory_order_check CHECK (("order" >= 0))
);


ALTER TABLE public.api_skillcategory OWNER TO cv_user;

--
-- Name: api_skillcategory_id_seq; Type: SEQUENCE; Schema: public; Owner: cv_user
--

ALTER TABLE public.api_skillcategory ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_skillcategory_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_skillitem; Type: TABLE; Schema: public; Owner: cv_user
--

CREATE TABLE public.api_skillitem (
    id bigint NOT NULL,
    name character varying(200) NOT NULL,
    "order" integer NOT NULL,
    category_id bigint NOT NULL,
    CONSTRAINT api_skillitem_order_check CHECK (("order" >= 0))
);


ALTER TABLE public.api_skillitem OWNER TO cv_user;

--
-- Name: api_skillitem_id_seq; Type: SEQUENCE; Schema: public; Owner: cv_user
--

ALTER TABLE public.api_skillitem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_skillitem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_softskill; Type: TABLE; Schema: public; Owner: cv_user
--

CREATE TABLE public.api_softskill (
    id bigint NOT NULL,
    skill character varying(100) NOT NULL,
    description text NOT NULL,
    "order" integer NOT NULL,
    CONSTRAINT api_softskill_order_check CHECK (("order" >= 0))
);


ALTER TABLE public.api_softskill OWNER TO cv_user;

--
-- Name: api_softskill_id_seq; Type: SEQUENCE; Schema: public; Owner: cv_user
--

ALTER TABLE public.api_softskill ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_softskill_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_systemarchitecture; Type: TABLE; Schema: public; Owner: cv_user
--

CREATE TABLE public.api_systemarchitecture (
    id bigint NOT NULL,
    title character varying(255) NOT NULL,
    description text NOT NULL,
    icon character varying(255) NOT NULL,
    "order" integer NOT NULL,
    items_discussed character varying(500) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    external_link character varying(200) NOT NULL
);


ALTER TABLE public.api_systemarchitecture OWNER TO cv_user;

--
-- Name: api_systemarchitecture_id_seq; Type: SEQUENCE; Schema: public; Owner: cv_user
--

ALTER TABLE public.api_systemarchitecture ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_systemarchitecture_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_userprofile; Type: TABLE; Schema: public; Owner: cv_user
--

CREATE TABLE public.api_userprofile (
    id bigint NOT NULL,
    role character varying(120) NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.api_userprofile OWNER TO cv_user;

--
-- Name: api_userprofile_id_seq; Type: SEQUENCE; Schema: public; Owner: cv_user
--

ALTER TABLE public.api_userprofile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_userprofile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: cv_user
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO cv_user;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: cv_user
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: cv_user
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO cv_user;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: cv_user
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: cv_user
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO cv_user;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: cv_user
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: cv_user
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO cv_user;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: cv_user
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO cv_user;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: cv_user
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: cv_user
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: cv_user
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO cv_user;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: cv_user
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: cv_user
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO cv_user;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: cv_user
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: cv_user
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO cv_user;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: cv_user
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: cv_user
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO cv_user;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: cv_user
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: cv_user
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO cv_user;

--
-- Data for Name: api_about; Type: TABLE DATA; Schema: public; Owner: cv_user
--

COPY public.api_about (id, headline, summary, profile_id) FROM stdin;
1	Career Summary	A tech enthusiast with over 5 years experience. I have expertise in building fullstack web apps with a strong focus on backend systems and cloud architecture.	2
\.


--
-- Data for Name: api_aboutparagraph; Type: TABLE DATA; Schema: public; Owner: cv_user
--

COPY public.api_aboutparagraph (id, content, "order", about_id) FROM stdin;
\.


--
-- Data for Name: api_architecture; Type: TABLE DATA; Schema: public; Owner: cv_user
--

COPY public.api_architecture (id, title, description, image, "order") FROM stdin;
\.


--
-- Data for Name: api_architecturelink; Type: TABLE DATA; Schema: public; Owner: cv_user
--

COPY public.api_architecturelink (id, label, href, "order", architecture_id) FROM stdin;
\.


--
-- Data for Name: api_architectureservice; Type: TABLE DATA; Schema: public; Owner: cv_user
--

COPY public.api_architectureservice (id, name, "order", architecture_id) FROM stdin;
\.


--
-- Data for Name: api_article; Type: TABLE DATA; Schema: public; Owner: cv_user
--

COPY public.api_article (id, title, description, body, tags, slug, created_at, updated_at) FROM stdin;
1	Getting Started with Cloud Computing	A beginner-friendly introduction to cloud computing and why it matters in modern application development.	Cloud computing has transformed how applications are built, deployed, and scaled. Instead of relying on physical servers, developers can now use on-demand infrastructure provided by platforms like Amazon Web Services, Microsoft Azure, and Google Cloud Platform. This shift allows businesses to reduce upfront costs while gaining flexibility and reliability in their systems.\r\n\r\nOne of the biggest advantages of the cloud is scalability. Applications can automatically handle increased traffic without manual intervention, making it ideal for startups and growing businesses. Services such as virtual machines, managed databases, and serverless functions allow developers to focus more on building features rather than managing infrastructure.\r\n\r\nHowever, adopting cloud computing also comes with responsibilities, especially around security and cost management. Misconfigured resources can lead to vulnerabilities or unexpected expenses. Understanding best practices and continuously monitoring your environment ensures that you get the full benefits of the	cloud, aws, devops, beginners	getting-started-with-cloud-computing	2026-04-20 10:20:46.567985+03	2026-04-20 10:20:46.567999+03
2	Building REST APIs with Django REST Framework	A practical guide to creating scalable and secure APIs using Django REST Framework.	Building APIs is a core skill for modern backend development, and Django REST Framework makes it efficient and structured. It provides powerful tools like serializers, viewsets, and routers that reduce boilerplate code while maintaining flexibility. With DRF, you can quickly turn your Django models into fully functional APIs.\r\n\r\nOne of the key strengths of DRF is its authentication and permission system. Whether you’re using token-based authentication or session-based login, you can control exactly who accesses your data. This becomes especially important when building applications with user-specific content, such as profiles, dashboards, or multi-tenant systems.\r\n\r\nTo build production-ready APIs, you also need to think beyond just CRUD operations. Pagination, filtering, validation, and proper error handling are essential for a good developer and user experience. Structuring your API well from the beginning will save you significant time as your application grows.	django, api, backend, drf	building-rest-apis-with-django-rest-framework	2026-04-20 10:22:03.486492+03	2026-04-20 10:22:03.486505+03
\.


--
-- Data for Name: api_corestrength; Type: TABLE DATA; Schema: public; Owner: cv_user
--

COPY public.api_corestrength (id, pillar, description, "order", about_id) FROM stdin;
\.


--
-- Data for Name: api_duty; Type: TABLE DATA; Schema: public; Owner: cv_user
--

COPY public.api_duty (id, description, "order", experience_id) FROM stdin;
\.


--
-- Data for Name: api_education; Type: TABLE DATA; Schema: public; Owner: cv_user
--

COPY public.api_education (id, institution, qualification, start_year, end_year, profile_id, "order", description) FROM stdin;
1	Africa Nazarene University	Bsc. Computer Science	2014	2018	2	0	Coursework in algorithms, data structures, operating systems, and software design patterns.
2	AWS	Solutions Architect	2025	2025	2	0	Learned to design highly available, secure, and scalable architectures aligned with AWS best practices.
5	Self	React | Fronted Development	2024	2025	2	1	"Built interactive and responsive user interfaces using React, focusing on component-based architecture, state management, and API integration.
6	Django	Django | Backend Development	2025	2025	2	1	Developed backend systems using Django and Django REST Framework, implementing RESTful APIs, authentication, and database-driven applications.
3	AWS	Cloud Practitioner	2025	2025	2	0	Built a foundational understanding of AWS services, cloud costing, and security best practices.
4	Kabaa High School	Kenya Certificate of Secondary Education	2003	2006	2	0	Completed Kenya Certificate of Secondary Education (KCSE) with core academic training.
\.


--
-- Data for Name: api_experience; Type: TABLE DATA; Schema: public; Owner: cv_user
--

COPY public.api_experience (id, company, role, start_date, end_date, description, "order", profile_id) FROM stdin;
1	Kimangi Enteprises	Manager	2020-01-10	2025-12-30	Improved rent collection through automated debt reminders, increasing timely payments by 35%.\r\nStreamlined business processes and operational workflows, enhancing overall efficiency and effectiveness by over 70%.\r\nExecuted debt recovery in full compliance with legal frameworks, due process, and fairness.\r\nInitiated and managed vacate processes in accordance with legal procedures while ensuring fairness to tenants.\r\nProvided regular updates to stakeholders and ensured actionable follow-through on recommendations	1	2
3	KASNEB	Intern	2018-03-09	2018-08-31	Assisted in network optimization and troubleshooting to improve system performance.\r\nInstalled and configured new hardware and software, ensuring smooth IT operations.\r\nProvided timely support to end users through multiple support channels.\r\nContributed to database design, development, and maintenance for organizational needs.\r\nMaintained IT systems to ensure security, reliability, and operational continuity.	3	2
2	Telmac Solutions Cyber Cafe	Founder & Manager / Network Admin & Desktop Support	2020-03-05	2023-09-28	Launched and managed a profitable cyber café and internet services venture, generating a consistent net profit of over KES 30,000 per month.\r\nExpanded revenue streams by supplying internet services to nearby businesses and residential clients.\r\nEstablished and maintained a secure local area network (LAN), ensuring reliable connectivity for all customers.\r\nLeveraged government platforms (eCitizen, NTSA, KRA) to provide value-added services, increasing daily transactions and customer retention.\r\nProvided technical support for walk-in clients, assisting with software navigation, printing, scanning, and troubleshooting	2	2
\.


--
-- Data for Name: api_featuredproject; Type: TABLE DATA; Schema: public; Owner: cv_user
--

COPY public.api_featuredproject (id, title, description, features, demo_link, github, updated_at, is_featured, "order") FROM stdin;
1	GlucoTrack AI (Health Monitoring App)	A full-stack web application for tracking blood sugar levels, visualizing trends, and generating AI-powered health insights for users.	User authentication and personalized dashboards\r\nBlood sugar data entry and history tracking\r\nInteractive charts and trend visualization\r\nAI-generated health reports and recommendations\r\nExportable reports (PDF/print-ready)	https://www.github.com/gluco-ai	https://www.github.com/gluco-ai	2026-04-16 14:21:27.77626+03	f	0
2	Cloud CV Portfolio Platform	A dynamic portfolio web application where users can create, update, and manage professional CVs with a Django REST backend and React frontend.	User registration and profile management\r\nCRUD operations for experience, education, and skills\r\nREST API with token-based authentication\r\nResponsive React frontend interface\r\nPostgreSQL-backed data persistence	https://www.github.com/cloud_cv	https://www.github.com/cloud_cv	2026-04-16 14:22:54.804851+03	f	0
3	AWS Infrastructure Automation with Terraform	An infrastructure-as-code project that provisions a secure AWS environment with a web server and database using Terraform.	Custom VPC with public and private subnets\r\nEC2 web server deployment in public subnet\r\nPrivate RDS/DB instance with restricted access\r\nSecurity groups with least-privilege rules\r\nAutomated provisioning and teardown with Terraform	https://www.github.com/terra_raise	https://www.github.com/terra_raise	2026-04-16 14:24:30.989179+03	t	0
4	Updated Portfolio Platform	Updated description				2026-04-16 15:14:54.819786+03	f	1
\.


--
-- Data for Name: api_hero; Type: TABLE DATA; Schema: public; Owner: cv_user
--

COPY public.api_hero (id, heading, subheading, cta_text, "order") FROM stdin;
1	Welcome to My Portfolio	Cloud Engineer & Solutions Architect	View My Work	0
\.


--
-- Data for Name: api_profile; Type: TABLE DATA; Schema: public; Owner: cv_user
--

COPY public.api_profile (id, name, title, "interestStatement", location, email, github, "linkedIn", updated_at, "resumeLink", user_id) FROM stdin;
1								2026-04-16 10:02:40.380535+03		1
2	Muiruri	Solutions Architect	Levraging Technology to create solutions to everyday challenges.	Nairobi	mwanjose@gmail.com	https://www.github.com/muiruri3000	https://www.linkedIn.com/muiruri_joseph	2026-04-16 10:07:58.169586+03	https://www.resume.com/resume	2
\.


--
-- Data for Name: api_profileskill; Type: TABLE DATA; Schema: public; Owner: cv_user
--

COPY public.api_profileskill (id, profile_id, skill_id) FROM stdin;
\.


--
-- Data for Name: api_skill; Type: TABLE DATA; Schema: public; Owner: cv_user
--

COPY public.api_skill (id, name) FROM stdin;
8	Python
9	Django / Django Rest Framework
10	React
11	Postgres
12	AWS Cloud
13	Linux / Bash
\.


--
-- Data for Name: api_skillcategory; Type: TABLE DATA; Schema: public; Owner: cv_user
--

COPY public.api_skillcategory (id, category, "order") FROM stdin;
\.


--
-- Data for Name: api_skillitem; Type: TABLE DATA; Schema: public; Owner: cv_user
--

COPY public.api_skillitem (id, name, "order", category_id) FROM stdin;
\.


--
-- Data for Name: api_softskill; Type: TABLE DATA; Schema: public; Owner: cv_user
--

COPY public.api_softskill (id, skill, description, "order") FROM stdin;
1	Communication Skills	Communication	0
2	Adaptability	Adaptability	0
3	Leadership	Leadership	0
4	Conflict Resolution	Conflict Resolution	0
5	Emotional Intelligence	Emotional Intelligence	0
6	Problem Solving	Problem Solving	0
7	Teamwork	Teamwork	0
\.


--
-- Data for Name: api_systemarchitecture; Type: TABLE DATA; Schema: public; Owner: cv_user
--

COPY public.api_systemarchitecture (id, title, description, icon, "order", items_discussed, created_at, external_link) FROM stdin;
1	Building a Scalable Django REST API	A practical guide to structuring and scaling DRF APIs with authentication and best practices.	Code	0	Django, Django REST Framework, JWT Authentication, API Design, Pagination	2026-04-21 09:25:42.057581+03	https://example.com/django-rest-api
\.


--
-- Data for Name: api_userprofile; Type: TABLE DATA; Schema: public; Owner: cv_user
--

COPY public.api_userprofile (id, role, user_id) FROM stdin;
1	ADMIN	1
2	ADMIN	2
\.


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: cv_user
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: cv_user
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: cv_user
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add profile	7	add_profile
26	Can change profile	7	change_profile
27	Can delete profile	7	delete_profile
28	Can view profile	7	view_profile
29	Can add skill	8	add_skill
30	Can change skill	8	change_skill
31	Can delete skill	8	delete_skill
32	Can view skill	8	view_skill
33	Can add experience	9	add_experience
34	Can change experience	9	change_experience
35	Can delete experience	9	delete_experience
36	Can view experience	9	view_experience
37	Can add education	10	add_education
38	Can change education	10	change_education
39	Can delete education	10	delete_education
40	Can view education	10	view_education
41	Can add profile skill	11	add_profileskill
42	Can change profile skill	11	change_profileskill
43	Can delete profile skill	11	delete_profileskill
44	Can view profile skill	11	view_profileskill
45	Can add duty	12	add_duty
46	Can change duty	12	change_duty
47	Can delete duty	12	delete_duty
48	Can view duty	12	view_duty
49	Can add about	13	add_about
50	Can change about	13	change_about
51	Can delete about	13	delete_about
52	Can view about	13	view_about
53	Can add about paragraph	14	add_aboutparagraph
54	Can change about paragraph	14	change_aboutparagraph
55	Can delete about paragraph	14	delete_aboutparagraph
56	Can view about paragraph	14	view_aboutparagraph
57	Can add core strength	15	add_corestrength
58	Can change core strength	15	change_corestrength
59	Can delete core strength	15	delete_corestrength
60	Can view core strength	15	view_corestrength
61	Can add hero	16	add_hero
62	Can change hero	16	change_hero
63	Can delete hero	16	delete_hero
64	Can view hero	16	view_hero
65	Can add featured project	17	add_featuredproject
66	Can change featured project	17	change_featuredproject
67	Can delete featured project	17	delete_featuredproject
68	Can view featured project	17	view_featuredproject
69	Can add skill category	18	add_skillcategory
70	Can change skill category	18	change_skillcategory
71	Can delete skill category	18	delete_skillcategory
72	Can view skill category	18	view_skillcategory
73	Can add skill item	19	add_skillitem
74	Can change skill item	19	change_skillitem
75	Can delete skill item	19	delete_skillitem
76	Can view skill item	19	view_skillitem
77	Can add soft skill	20	add_softskill
78	Can change soft skill	20	change_softskill
79	Can delete soft skill	20	delete_softskill
80	Can view soft skill	20	view_softskill
81	Can add architecture	21	add_architecture
82	Can change architecture	21	change_architecture
83	Can delete architecture	21	delete_architecture
84	Can view architecture	21	view_architecture
85	Can add architecture link	22	add_architecturelink
86	Can change architecture link	22	change_architecturelink
87	Can delete architecture link	22	delete_architecturelink
88	Can view architecture link	22	view_architecturelink
89	Can add architecture service	23	add_architectureservice
90	Can change architecture service	23	change_architectureservice
91	Can delete architecture service	23	delete_architectureservice
92	Can view architecture service	23	view_architectureservice
93	Can add article	24	add_article
94	Can change article	24	change_article
95	Can delete article	24	delete_article
96	Can view article	24	view_article
97	Can add user profile	25	add_userprofile
98	Can change user profile	25	change_userprofile
99	Can delete user profile	25	delete_userprofile
100	Can view user profile	25	view_userprofile
101	Can add system architecture	26	add_systemarchitecture
102	Can change system architecture	26	change_systemarchitecture
103	Can delete system architecture	26	delete_systemarchitecture
104	Can view system architecture	26	view_systemarchitecture
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: cv_user
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
1	pbkdf2_sha256$1000000$ooQcPsUe3043vu8ps2xSDs$44Vdl0kf2R/PZE4K4DA+E2oeNEZOjZFJZyvrZ+lkJPY=	2026-04-16 11:18:06.043333+03	t	mo			14s01abt017@gmail.com	t	t	2026-04-16 10:01:25.077076+03
2	pbkdf2_sha256$1000000$VPxk7TGqZNUvS7gee8edZu$uYM5fWLJbR+K4AgMZDt3h6HZx4tRA9hJSlYsWmrq3oI=	2026-04-16 11:19:11.978259+03	t	Joseph				t	t	2026-04-16 10:07:41+03
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: cv_user
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: cv_user
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: cv_user
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2026-04-16 10:03:56.884538+03	1	mo - ADMIN	2	[{"changed": {"fields": ["Role"]}}]	25	1
2	2026-04-16 10:07:43.078239+03	2	Joseph	1	[{"added": {}}]	4	1
3	2026-04-16 10:07:58.172396+03	2	Muiruri	1	[{"added": {}}]	7	1
4	2026-04-16 11:17:24.50967+03	2	Joseph - ADMIN	2	[{"changed": {"fields": ["Role"]}}]	25	1
5	2026-04-16 11:18:56.751673+03	2	Joseph	2	[{"changed": {"fields": ["Staff status", "Superuser status"]}}]	4	1
6	2026-04-16 11:20:14.4672+03	1	Education object (1)	1	[{"added": {}}]	10	2
7	2026-04-16 11:22:02.665333+03	2	Education object (2)	1	[{"added": {}}]	10	2
8	2026-04-16 11:22:48.537585+03	3	Education object (3)	1	[{"added": {}}]	10	2
9	2026-04-16 11:24:22.916367+03	4	Education object (4)	1	[{"added": {}}]	10	2
10	2026-04-16 11:25:29.523074+03	1	Communication Skills	1	[{"added": {}}]	8	2
11	2026-04-16 11:25:33.04006+03	1	ProfileSkill object (1)	1	[{"added": {}}]	11	2
12	2026-04-16 11:25:45.211387+03	1	ProfileSkill object (1)	2	[]	11	2
13	2026-04-16 11:26:55.756162+03	2	Teamwork	1	[{"added": {}}]	8	2
14	2026-04-16 11:27:09.878934+03	3	Adaptability	1	[{"added": {}}]	8	2
15	2026-04-16 11:27:29.866386+03	4	Problem Solving	1	[{"added": {}}]	8	2
16	2026-04-16 11:28:12.90448+03	5	Leadership	1	[{"added": {}}]	8	2
17	2026-04-16 11:28:37.904477+03	6	Emotional Intelligence	1	[{"added": {}}]	8	2
18	2026-04-16 11:29:01.783325+03	7	Conflict Resolution	1	[{"added": {}}]	8	2
19	2026-04-16 11:58:05.866706+03	1	Career Summary	1	[{"added": {}}]	13	2
20	2026-04-16 11:59:30.974739+03	1	Communication Skills	1	[{"added": {}}]	20	2
21	2026-04-16 11:59:46.27728+03	2	Adaptability	1	[{"added": {}}]	20	2
22	2026-04-16 12:00:03.46356+03	3	Leadership	1	[{"added": {}}]	20	2
23	2026-04-16 12:00:24.800233+03	4	Conflict Resolution	1	[{"added": {}}]	20	2
24	2026-04-16 12:00:46.009938+03	5	Emotional Intelligence	1	[{"added": {}}]	20	2
25	2026-04-16 12:02:06.683733+03	6	Problem Solving	1	[{"added": {}}]	20	2
26	2026-04-16 12:02:24.268842+03	7	Teamwork	1	[{"added": {}}]	20	2
27	2026-04-16 12:02:47.051562+03	7	Conflict Resolution	3		8	2
28	2026-04-16 12:02:47.051617+03	6	Emotional Intelligence	3		8	2
29	2026-04-16 12:02:47.051646+03	5	Leadership	3		8	2
30	2026-04-16 12:02:47.051669+03	4	Problem Solving	3		8	2
31	2026-04-16 12:02:47.051686+03	3	Adaptability	3		8	2
32	2026-04-16 12:02:47.051705+03	2	Teamwork	3		8	2
33	2026-04-16 12:02:47.051725+03	1	Communication Skills	3		8	2
34	2026-04-16 12:03:36.656615+03	8	Python	1	[{"added": {}}]	8	2
35	2026-04-16 12:04:01.212608+03	9	Django / Django Rest Framework	1	[{"added": {}}]	8	2
36	2026-04-16 12:04:26.730831+03	10	React	1	[{"added": {}}]	8	2
37	2026-04-16 12:04:46.234294+03	11	Postgres	1	[{"added": {}}]	8	2
38	2026-04-16 12:04:56.822244+03	12	AWS Cloud	1	[{"added": {}}]	8	2
39	2026-04-16 12:05:15.970692+03	13	Linux / Bash	1	[{"added": {}}]	8	2
40	2026-04-16 14:21:27.809858+03	1	GlucoTrack AI (Health Monitoring App)	1	[{"added": {}}]	17	2
41	2026-04-16 14:22:54.808978+03	2	Cloud CV Portfolio Platform	1	[{"added": {}}]	17	2
42	2026-04-16 14:24:30.990028+03	3	AWS Infrastructure Automation with Terraform	1	[{"added": {}}]	17	2
43	2026-04-17 12:30:12.341425+03	5	Education object (5)	1	[{"added": {}}]	10	2
44	2026-04-17 12:34:18.815567+03	6	Education object (6)	1	[{"added": {}}]	10	2
45	2026-04-17 12:36:06.983924+03	3	Education object (3)	2	[{"changed": {"fields": ["Institution", "Qualification"]}}]	10	2
46	2026-04-17 12:37:33.931388+03	4	Education object (4)	2	[{"changed": {"fields": ["Description"]}}]	10	2
47	2026-04-17 12:58:04.572947+03	1	Experience object (1)	1	[{"added": {}}]	9	2
48	2026-04-17 14:47:24.354158+03	2	Experience object (2)	1	[{"added": {}}]	9	2
49	2026-04-17 14:48:59.378858+03	3	Experience object (3)	1	[{"added": {}}]	9	2
50	2026-04-17 15:00:26.128942+03	2	Experience object (2)	2	[{"changed": {"fields": ["Description"]}}]	9	2
51	2026-04-20 10:20:46.873168+03	1	Getting Started with Cloud Computing	1	[{"added": {}}]	24	2
52	2026-04-20 10:22:03.487358+03	2	Building REST APIs with Django REST Framework	1	[{"added": {}}]	24	2
53	2026-04-21 09:25:42.058821+03	1	Building a Scalable Django REST API	1	[{"added": {}}]	26	2
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: cv_user
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	api	profile
8	api	skill
9	api	experience
10	api	education
11	api	profileskill
12	api	duty
13	api	about
14	api	aboutparagraph
15	api	corestrength
16	api	hero
17	api	featuredproject
18	api	skillcategory
19	api	skillitem
20	api	softskill
21	api	architecture
22	api	architecturelink
23	api	architectureservice
24	api	article
25	api	userprofile
26	api	systemarchitecture
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: cv_user
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-04-16 08:41:48.991025+03
2	auth	0001_initial	2026-04-16 08:41:50.702128+03
3	admin	0001_initial	2026-04-16 08:41:50.967936+03
4	admin	0002_logentry_remove_auto_add	2026-04-16 08:41:50.998683+03
5	admin	0003_logentry_add_action_flag_choices	2026-04-16 08:41:51.028323+03
6	api	0001_initial	2026-04-16 08:41:51.807853+03
7	api	0002_profile_resumelink	2026-04-16 08:41:51.834939+03
8	api	0003_rename_bio_profile_interestestatement_and_more	2026-04-16 08:41:51.882564+03
9	api	0004_rename_interestestatement_profile_intereststatement	2026-04-16 08:41:51.905065+03
10	api	0005_rename_linkedin_profile_linkedin	2026-04-16 08:41:51.929305+03
11	api	0006_duty	2026-04-16 08:41:52.056925+03
12	api	0007_rename_qualification_education_qualifs	2026-04-16 08:41:52.075499+03
13	api	0008_rename_qualifs_education_qualification	2026-04-16 08:41:52.095206+03
14	api	0009_alter_education_options_education_order	2026-04-16 08:41:52.135644+03
15	api	0010_about_aboutparagraph	2026-04-16 08:41:52.572253+03
16	api	0011_corestrength	2026-04-16 08:41:52.788694+03
17	api	0012_hero	2026-04-16 08:41:52.894447+03
18	api	0013_hero_order	2026-04-16 08:41:52.931147+03
19	api	0014_featuredproject	2026-04-16 08:41:53.044636+03
20	api	0015_featuredproject_order	2026-04-16 08:41:53.080739+03
21	api	0016_skillcategory_skillitem	2026-04-16 08:41:53.254454+03
22	api	0017_softskill	2026-04-16 08:41:53.520672+03
23	api	0018_architecture_architecturelink_architectureservice	2026-04-16 08:41:54.027802+03
24	api	0019_article	2026-04-16 08:41:54.277157+03
25	api	0020_userprofile	2026-04-16 08:41:54.435025+03
26	api	0021_profile_user_alter_userprofile_user	2026-04-16 08:41:54.58037+03
27	contenttypes	0002_remove_content_type_name	2026-04-16 08:41:54.672775+03
28	auth	0002_alter_permission_name_max_length	2026-04-16 08:41:54.707302+03
29	auth	0003_alter_user_email_max_length	2026-04-16 08:41:54.764886+03
30	auth	0004_alter_user_username_opts	2026-04-16 08:41:54.804934+03
31	auth	0005_alter_user_last_login_null	2026-04-16 08:41:54.842457+03
32	auth	0006_require_contenttypes_0002	2026-04-16 08:41:54.850416+03
33	auth	0007_alter_validators_add_error_messages	2026-04-16 08:41:54.885185+03
34	auth	0008_alter_user_username_max_length	2026-04-16 08:41:54.955483+03
35	auth	0009_alter_user_last_name_max_length	2026-04-16 08:41:55.004479+03
36	auth	0010_alter_group_name_max_length	2026-04-16 08:41:55.03998+03
37	auth	0011_update_proxy_permissions	2026-04-16 08:41:55.078178+03
38	auth	0012_alter_user_first_name_max_length	2026-04-16 08:41:55.101867+03
39	sessions	0001_initial	2026-04-16 08:41:55.348936+03
40	api	0022_education_description	2026-04-17 11:16:27.402874+03
41	api	0023_systemarchitecture	2026-04-21 09:10:56.317317+03
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: cv_user
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
xg3bc86v7fbi0v6e4wrim1980hbzjxul	.eJxVjE0OwiAYRO_C2pACBYtL956BfH9I1dCktCvj3W2TLnQ5897MWyVYl5LWJnMaWV2UVaffDoGeUnfAD6j3SdNUl3lEvSv6oE3fJpbX9XD_Dgq0sq0dBOm84cENhs8gmbMzIXQGKfsYTG8FM2-h90IYfeejQchusIShJ1KfL_XtOLo:1wDHwN:ZA_V0qZol_NjL7TD1bPQnzf9BCYl-e7VwXslJTtx0zo	2026-04-30 11:19:11.986958+03
\.


--
-- Name: api_about_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cv_user
--

SELECT pg_catalog.setval('public.api_about_id_seq', 1, true);


--
-- Name: api_aboutparagraph_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cv_user
--

SELECT pg_catalog.setval('public.api_aboutparagraph_id_seq', 1, false);


--
-- Name: api_architecture_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cv_user
--

SELECT pg_catalog.setval('public.api_architecture_id_seq', 1, false);


--
-- Name: api_architecturelink_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cv_user
--

SELECT pg_catalog.setval('public.api_architecturelink_id_seq', 1, false);


--
-- Name: api_architectureservice_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cv_user
--

SELECT pg_catalog.setval('public.api_architectureservice_id_seq', 1, false);


--
-- Name: api_article_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cv_user
--

SELECT pg_catalog.setval('public.api_article_id_seq', 2, true);


--
-- Name: api_corestrength_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cv_user
--

SELECT pg_catalog.setval('public.api_corestrength_id_seq', 1, false);


--
-- Name: api_duty_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cv_user
--

SELECT pg_catalog.setval('public.api_duty_id_seq', 1, false);


--
-- Name: api_education_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cv_user
--

SELECT pg_catalog.setval('public.api_education_id_seq', 6, true);


--
-- Name: api_experience_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cv_user
--

SELECT pg_catalog.setval('public.api_experience_id_seq', 3, true);


--
-- Name: api_featuredproject_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cv_user
--

SELECT pg_catalog.setval('public.api_featuredproject_id_seq', 4, true);


--
-- Name: api_hero_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cv_user
--

SELECT pg_catalog.setval('public.api_hero_id_seq', 1, true);


--
-- Name: api_profile_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cv_user
--

SELECT pg_catalog.setval('public.api_profile_id_seq', 2, true);


--
-- Name: api_profileskill_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cv_user
--

SELECT pg_catalog.setval('public.api_profileskill_id_seq', 1, true);


--
-- Name: api_skill_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cv_user
--

SELECT pg_catalog.setval('public.api_skill_id_seq', 13, true);


--
-- Name: api_skillcategory_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cv_user
--

SELECT pg_catalog.setval('public.api_skillcategory_id_seq', 1, false);


--
-- Name: api_skillitem_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cv_user
--

SELECT pg_catalog.setval('public.api_skillitem_id_seq', 1, false);


--
-- Name: api_softskill_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cv_user
--

SELECT pg_catalog.setval('public.api_softskill_id_seq', 7, true);


--
-- Name: api_systemarchitecture_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cv_user
--

SELECT pg_catalog.setval('public.api_systemarchitecture_id_seq', 1, true);


--
-- Name: api_userprofile_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cv_user
--

SELECT pg_catalog.setval('public.api_userprofile_id_seq', 2, true);


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cv_user
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cv_user
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cv_user
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 104, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cv_user
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cv_user
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 2, true);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cv_user
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cv_user
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 53, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cv_user
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 26, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cv_user
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 41, true);


--
-- Name: api_about api_about_pkey; Type: CONSTRAINT; Schema: public; Owner: cv_user
--

ALTER TABLE ONLY public.api_about
    ADD CONSTRAINT api_about_pkey PRIMARY KEY (id);


--
-- Name: api_about api_about_profile_id_key; Type: CONSTRAINT; Schema: public; Owner: cv_user
--

ALTER TABLE ONLY public.api_about
    ADD CONSTRAINT api_about_profile_id_key UNIQUE (profile_id);


--
-- Name: api_aboutparagraph api_aboutparagraph_pkey; Type: CONSTRAINT; Schema: public; Owner: cv_user
--

ALTER TABLE ONLY public.api_aboutparagraph
    ADD CONSTRAINT api_aboutparagraph_pkey PRIMARY KEY (id);


--
-- Name: api_architecture api_architecture_pkey; Type: CONSTRAINT; Schema: public; Owner: cv_user
--

ALTER TABLE ONLY public.api_architecture
    ADD CONSTRAINT api_architecture_pkey PRIMARY KEY (id);


--
-- Name: api_architecturelink api_architecturelink_pkey; Type: CONSTRAINT; Schema: public; Owner: cv_user
--

ALTER TABLE ONLY public.api_architecturelink
    ADD CONSTRAINT api_architecturelink_pkey PRIMARY KEY (id);


--
-- Name: api_architectureservice api_architectureservice_pkey; Type: CONSTRAINT; Schema: public; Owner: cv_user
--

ALTER TABLE ONLY public.api_architectureservice
    ADD CONSTRAINT api_architectureservice_pkey PRIMARY KEY (id);


--
-- Name: api_article api_article_pkey; Type: CONSTRAINT; Schema: public; Owner: cv_user
--

ALTER TABLE ONLY public.api_article
    ADD CONSTRAINT api_article_pkey PRIMARY KEY (id);


--
-- Name: api_article api_article_slug_key; Type: CONSTRAINT; Schema: public; Owner: cv_user
--

ALTER TABLE ONLY public.api_article
    ADD CONSTRAINT api_article_slug_key UNIQUE (slug);


--
-- Name: api_corestrength api_corestrength_pkey; Type: CONSTRAINT; Schema: public; Owner: cv_user
--

ALTER TABLE ONLY public.api_corestrength
    ADD CONSTRAINT api_corestrength_pkey PRIMARY KEY (id);


--
-- Name: api_duty api_duty_pkey; Type: CONSTRAINT; Schema: public; Owner: cv_user
--

ALTER TABLE ONLY public.api_duty
    ADD CONSTRAINT api_duty_pkey PRIMARY KEY (id);


--
-- Name: api_education api_education_pkey; Type: CONSTRAINT; Schema: public; Owner: cv_user
--

ALTER TABLE ONLY public.api_education
    ADD CONSTRAINT api_education_pkey PRIMARY KEY (id);


--
-- Name: api_experience api_experience_pkey; Type: CONSTRAINT; Schema: public; Owner: cv_user
--

ALTER TABLE ONLY public.api_experience
    ADD CONSTRAINT api_experience_pkey PRIMARY KEY (id);


--
-- Name: api_featuredproject api_featuredproject_pkey; Type: CONSTRAINT; Schema: public; Owner: cv_user
--

ALTER TABLE ONLY public.api_featuredproject
    ADD CONSTRAINT api_featuredproject_pkey PRIMARY KEY (id);


--
-- Name: api_hero api_hero_pkey; Type: CONSTRAINT; Schema: public; Owner: cv_user
--

ALTER TABLE ONLY public.api_hero
    ADD CONSTRAINT api_hero_pkey PRIMARY KEY (id);


--
-- Name: api_profile api_profile_pkey; Type: CONSTRAINT; Schema: public; Owner: cv_user
--

ALTER TABLE ONLY public.api_profile
    ADD CONSTRAINT api_profile_pkey PRIMARY KEY (id);


--
-- Name: api_profile api_profile_user_id_key; Type: CONSTRAINT; Schema: public; Owner: cv_user
--

ALTER TABLE ONLY public.api_profile
    ADD CONSTRAINT api_profile_user_id_key UNIQUE (user_id);


--
-- Name: api_profileskill api_profileskill_pkey; Type: CONSTRAINT; Schema: public; Owner: cv_user
--

ALTER TABLE ONLY public.api_profileskill
    ADD CONSTRAINT api_profileskill_pkey PRIMARY KEY (id);


--
-- Name: api_skill api_skill_name_key; Type: CONSTRAINT; Schema: public; Owner: cv_user
--

ALTER TABLE ONLY public.api_skill
    ADD CONSTRAINT api_skill_name_key UNIQUE (name);


--
-- Name: api_skill api_skill_pkey; Type: CONSTRAINT; Schema: public; Owner: cv_user
--

ALTER TABLE ONLY public.api_skill
    ADD CONSTRAINT api_skill_pkey PRIMARY KEY (id);


--
-- Name: api_skillcategory api_skillcategory_pkey; Type: CONSTRAINT; Schema: public; Owner: cv_user
--

ALTER TABLE ONLY public.api_skillcategory
    ADD CONSTRAINT api_skillcategory_pkey PRIMARY KEY (id);


--
-- Name: api_skillitem api_skillitem_pkey; Type: CONSTRAINT; Schema: public; Owner: cv_user
--

ALTER TABLE ONLY public.api_skillitem
    ADD CONSTRAINT api_skillitem_pkey PRIMARY KEY (id);


--
-- Name: api_softskill api_softskill_pkey; Type: CONSTRAINT; Schema: public; Owner: cv_user
--

ALTER TABLE ONLY public.api_softskill
    ADD CONSTRAINT api_softskill_pkey PRIMARY KEY (id);


--
-- Name: api_softskill api_softskill_skill_key; Type: CONSTRAINT; Schema: public; Owner: cv_user
--

ALTER TABLE ONLY public.api_softskill
    ADD CONSTRAINT api_softskill_skill_key UNIQUE (skill);


--
-- Name: api_systemarchitecture api_systemarchitecture_pkey; Type: CONSTRAINT; Schema: public; Owner: cv_user
--

ALTER TABLE ONLY public.api_systemarchitecture
    ADD CONSTRAINT api_systemarchitecture_pkey PRIMARY KEY (id);


--
-- Name: api_userprofile api_userprofile_pkey; Type: CONSTRAINT; Schema: public; Owner: cv_user
--

ALTER TABLE ONLY public.api_userprofile
    ADD CONSTRAINT api_userprofile_pkey PRIMARY KEY (id);


--
-- Name: api_userprofile api_userprofile_user_id_key; Type: CONSTRAINT; Schema: public; Owner: cv_user
--

ALTER TABLE ONLY public.api_userprofile
    ADD CONSTRAINT api_userprofile_user_id_key UNIQUE (user_id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: cv_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: cv_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: cv_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: cv_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: cv_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: cv_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: cv_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: cv_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: cv_user
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: cv_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: cv_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: cv_user
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: cv_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: cv_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: cv_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: cv_user
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: cv_user
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: api_aboutparagraph_about_id_e9e14a7c; Type: INDEX; Schema: public; Owner: cv_user
--

CREATE INDEX api_aboutparagraph_about_id_e9e14a7c ON public.api_aboutparagraph USING btree (about_id);


--
-- Name: api_architecturelink_architecture_id_5a20952b; Type: INDEX; Schema: public; Owner: cv_user
--

CREATE INDEX api_architecturelink_architecture_id_5a20952b ON public.api_architecturelink USING btree (architecture_id);


--
-- Name: api_architectureservice_architecture_id_46eee2e7; Type: INDEX; Schema: public; Owner: cv_user
--

CREATE INDEX api_architectureservice_architecture_id_46eee2e7 ON public.api_architectureservice USING btree (architecture_id);


--
-- Name: api_article_slug_a1957baa_like; Type: INDEX; Schema: public; Owner: cv_user
--

CREATE INDEX api_article_slug_a1957baa_like ON public.api_article USING btree (slug varchar_pattern_ops);


--
-- Name: api_corestrength_about_id_5025c610; Type: INDEX; Schema: public; Owner: cv_user
--

CREATE INDEX api_corestrength_about_id_5025c610 ON public.api_corestrength USING btree (about_id);


--
-- Name: api_duty_experience_id_66c761c5; Type: INDEX; Schema: public; Owner: cv_user
--

CREATE INDEX api_duty_experience_id_66c761c5 ON public.api_duty USING btree (experience_id);


--
-- Name: api_education_profile_id_872759d2; Type: INDEX; Schema: public; Owner: cv_user
--

CREATE INDEX api_education_profile_id_872759d2 ON public.api_education USING btree (profile_id);


--
-- Name: api_experience_profile_id_e4dba2aa; Type: INDEX; Schema: public; Owner: cv_user
--

CREATE INDEX api_experience_profile_id_e4dba2aa ON public.api_experience USING btree (profile_id);


--
-- Name: api_profileskill_profile_id_1c399a6e; Type: INDEX; Schema: public; Owner: cv_user
--

CREATE INDEX api_profileskill_profile_id_1c399a6e ON public.api_profileskill USING btree (profile_id);


--
-- Name: api_profileskill_skill_id_c0b82440; Type: INDEX; Schema: public; Owner: cv_user
--

CREATE INDEX api_profileskill_skill_id_c0b82440 ON public.api_profileskill USING btree (skill_id);


--
-- Name: api_skill_name_3dcad775_like; Type: INDEX; Schema: public; Owner: cv_user
--

CREATE INDEX api_skill_name_3dcad775_like ON public.api_skill USING btree (name varchar_pattern_ops);


--
-- Name: api_skillitem_category_id_d7d95873; Type: INDEX; Schema: public; Owner: cv_user
--

CREATE INDEX api_skillitem_category_id_d7d95873 ON public.api_skillitem USING btree (category_id);


--
-- Name: api_softskill_skill_01378e06_like; Type: INDEX; Schema: public; Owner: cv_user
--

CREATE INDEX api_softskill_skill_01378e06_like ON public.api_softskill USING btree (skill varchar_pattern_ops);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: cv_user
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: cv_user
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: cv_user
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: cv_user
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: cv_user
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: cv_user
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: cv_user
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: cv_user
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: cv_user
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: cv_user
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: cv_user
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: cv_user
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: cv_user
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: api_about api_about_profile_id_2a355597_fk_api_profile_id; Type: FK CONSTRAINT; Schema: public; Owner: cv_user
--

ALTER TABLE ONLY public.api_about
    ADD CONSTRAINT api_about_profile_id_2a355597_fk_api_profile_id FOREIGN KEY (profile_id) REFERENCES public.api_profile(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_aboutparagraph api_aboutparagraph_about_id_e9e14a7c_fk_api_about_id; Type: FK CONSTRAINT; Schema: public; Owner: cv_user
--

ALTER TABLE ONLY public.api_aboutparagraph
    ADD CONSTRAINT api_aboutparagraph_about_id_e9e14a7c_fk_api_about_id FOREIGN KEY (about_id) REFERENCES public.api_about(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_architecturelink api_architecturelink_architecture_id_5a20952b_fk_api_archi; Type: FK CONSTRAINT; Schema: public; Owner: cv_user
--

ALTER TABLE ONLY public.api_architecturelink
    ADD CONSTRAINT api_architecturelink_architecture_id_5a20952b_fk_api_archi FOREIGN KEY (architecture_id) REFERENCES public.api_architecture(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_architectureservice api_architectureserv_architecture_id_46eee2e7_fk_api_archi; Type: FK CONSTRAINT; Schema: public; Owner: cv_user
--

ALTER TABLE ONLY public.api_architectureservice
    ADD CONSTRAINT api_architectureserv_architecture_id_46eee2e7_fk_api_archi FOREIGN KEY (architecture_id) REFERENCES public.api_architecture(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_corestrength api_corestrength_about_id_5025c610_fk_api_about_id; Type: FK CONSTRAINT; Schema: public; Owner: cv_user
--

ALTER TABLE ONLY public.api_corestrength
    ADD CONSTRAINT api_corestrength_about_id_5025c610_fk_api_about_id FOREIGN KEY (about_id) REFERENCES public.api_about(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_duty api_duty_experience_id_66c761c5_fk_api_experience_id; Type: FK CONSTRAINT; Schema: public; Owner: cv_user
--

ALTER TABLE ONLY public.api_duty
    ADD CONSTRAINT api_duty_experience_id_66c761c5_fk_api_experience_id FOREIGN KEY (experience_id) REFERENCES public.api_experience(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_education api_education_profile_id_872759d2_fk_api_profile_id; Type: FK CONSTRAINT; Schema: public; Owner: cv_user
--

ALTER TABLE ONLY public.api_education
    ADD CONSTRAINT api_education_profile_id_872759d2_fk_api_profile_id FOREIGN KEY (profile_id) REFERENCES public.api_profile(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_experience api_experience_profile_id_e4dba2aa_fk_api_profile_id; Type: FK CONSTRAINT; Schema: public; Owner: cv_user
--

ALTER TABLE ONLY public.api_experience
    ADD CONSTRAINT api_experience_profile_id_e4dba2aa_fk_api_profile_id FOREIGN KEY (profile_id) REFERENCES public.api_profile(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_profile api_profile_user_id_41309820_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: cv_user
--

ALTER TABLE ONLY public.api_profile
    ADD CONSTRAINT api_profile_user_id_41309820_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_profileskill api_profileskill_profile_id_1c399a6e_fk_api_profile_id; Type: FK CONSTRAINT; Schema: public; Owner: cv_user
--

ALTER TABLE ONLY public.api_profileskill
    ADD CONSTRAINT api_profileskill_profile_id_1c399a6e_fk_api_profile_id FOREIGN KEY (profile_id) REFERENCES public.api_profile(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_profileskill api_profileskill_skill_id_c0b82440_fk_api_skill_id; Type: FK CONSTRAINT; Schema: public; Owner: cv_user
--

ALTER TABLE ONLY public.api_profileskill
    ADD CONSTRAINT api_profileskill_skill_id_c0b82440_fk_api_skill_id FOREIGN KEY (skill_id) REFERENCES public.api_skill(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_skillitem api_skillitem_category_id_d7d95873_fk_api_skillcategory_id; Type: FK CONSTRAINT; Schema: public; Owner: cv_user
--

ALTER TABLE ONLY public.api_skillitem
    ADD CONSTRAINT api_skillitem_category_id_d7d95873_fk_api_skillcategory_id FOREIGN KEY (category_id) REFERENCES public.api_skillcategory(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_userprofile api_userprofile_user_id_5a1c1c92_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: cv_user
--

ALTER TABLE ONLY public.api_userprofile
    ADD CONSTRAINT api_userprofile_user_id_5a1c1c92_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: cv_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: cv_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: cv_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: cv_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: cv_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: cv_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: cv_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: cv_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: cv_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: pg_database_owner
--

GRANT ALL ON SCHEMA public TO cv_user;


--
-- PostgreSQL database dump complete
--

\unrestrict cvvhlijhVxMYO4RNLKrHPOVQFc7BZrE5dzU3bzXdW5UuPfFQiDXS39YAj9E5o4d

