# Generated by Django 6.0.1 on 2026-02-05 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_profile_resumelink'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='bio',
            new_name='interesteStatement',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='full_name',
            new_name='name',
        ),
    ]
