# Generated by Django 6.0.1 on 2026-02-06 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_bio_profile_interestestatement_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='interesteStatement',
            new_name='interestStatement',
        ),
    ]
