# Generated by Django 6.0.1 on 2026-02-06 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_interestestatement_profile_intereststatement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='linkedin',
            new_name='linkedIn',
        ),
    ]
