# Generated by Django 6.0.1 on 2026-02-10 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_duty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='qualification',
            new_name='qualifs',
        ),
    ]
