# Generated by Django 6.0.1 on 2026-02-10 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_qualification_education_qualifs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='qualifs',
            new_name='qualification',
        ),
    ]
