# Generated by Django 6.0.1 on 2026-02-10 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_qualifs_education_qualification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='education',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
