# Generated by Django 6.0.1 on 2026-02-10 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_about_aboutparagraph'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreStrength',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pillar', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_strengths', to='api.about')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
