# Generated by Django 6.0.1 on 2026-02-11 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_hero'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
