# Generated by Django 6.0.1 on 2026-02-11 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_featuredproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredproject',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
