# Generated by Django 6.0.1 on 2026-02-18 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_softskill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Architecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='architectures/')),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ArchitectureLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('href', models.URLField()),
                ('order', models.IntegerField(default=0)),
                ('architecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='api.architecture')),
            ],
        ),
        migrations.CreateModel(
            name='ArchitectureService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('architecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='api.architecture')),
            ],
        ),
    ]
