# Generated by Django 5.2.13 on 2026-04-17 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_profile_user_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
