# Generated by Django 5.2.13 on 2026-04-21 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_education_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemArchitecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('items_discussed', models.CharField(blank=True, help_text='Comma-separated list of items discussed in this architecture', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('external_link', models.URLField()),
            ],
        ),
    ]
