# Generated by Django 5.2.13 on 2026-04-30 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_systemarchitecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemarchitecture',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='systemarchitecture',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
