name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: cv_db
          POSTGRES_USER: cv_user
          POSTGRES_PASSWORD: postgres123
        ports:
        - 5432:5432
        options: >-
          --health-cmd="pg_isready -U cv_user -d cv_db" --health-interval=5s --health-timeout=5s --health-retries=20
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      working-directory: ./cv_backend
      run: |
        pip install -r requirements.txt

    # - name: Wait for Postgres
    #   run: |
    #     until pg_isready -h postgres -p 5432 -U cv_user; do
    #       echo "Waiting for postgres..."
    #       sleep 2
    #     done
    - name: Run Django migrations
      working-directory: ./cv_backend

      run: |
        python manage.py migrate

    # Set up React

    - name: Set Up Node
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Install React dependencies
      working-directory: /my-digital-canvas
      run: |
        npm install

    - name: Build React app
      working-directory: /my-digital-canvas
      run: |
        npm run build
